<?php 
/**
 * Virtina
 * @package    Virtina_Categorysidebar
 * @copyright  Copyright (c) 2015-2016 Virtina. (http://www.virtina.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_sidemenu = $this->customCategoriesMenuHtml(0,'level-top'); ?>
<?php $configCatNav = Mage::getStoreConfig('categorysidebar/general/enable'); ?>
<?php $configTitle = Mage::getStoreConfig('categorysidebar/general/title'); ?>
<?php if($configCatNav): ?>
	<?php if($_sidemenu): ?>
		<div class="cat-nav-container">
			<div class="block-title">
				<strong><span><?php echo $configTitle ?></span></strong>
			</div>
			<ul class="nav-content">
				<?php echo $_sidemenu ?>
			</ul>
		</div>
	<?php endif ?>
<?php endif ?>
